title: Ahmed Nassar
baseURL: /
params:
  color_scheme: light
  accent_color: violet
  header:
    type: header
    template: header
    title: nassar
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
      - type: action
        template: action
        label: Portfolio
        url: /portfolio/
        style: link
      - type: action
        template: action
        label: Blog
        url: /blog/
        style: link
      - type: action
        template: action
        label: About
        url: /about/
        style: link
      - type: action
        template: action
        label: Contact
        url: /contact/
        style: button
    logo_img: /images/Untitled (23).png
  footer:
    type: footer
    template: footer
    content: '&copy; 2021 Ahmed Nassar All Rights Reserved.'
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/anassar97'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        template: action
        label: Instagram
        url: 'https://www.instagram.com/anassar9'
        style: icon
        icon_class: fa-instagram
        new_window: true
  description: The personal site of Scientist and Creator Ahmed Nassar
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
