title: Ahmed Nassar
baseURL: /
params:
  color_scheme: light
  accent_color: violet
  footer:
    type: footer
    template: footer
    content: '&copy; 2021 Ahmed Nassar All Rights Reserved.'
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/anassar97'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        template: action
        label: Instagram
        url: 'https://www.instagram.com/anassar9'
        style: icon
        icon_class: fa-instagram
        new_window: true
  description: The personal site of Scientist and Creator Ahmed Nassar
  header:
    title: nassar
    logo_img_alt: lorem-ipsum
    has_nav: true
    nav_links:
      - label: Home
        url: lorem-ipsum
        style: link
        icon_class: lorem-ipsum
        new_window: false
        no_follow: false
        type: action
      - label: lorem-ipsum
        url: lorem-ipsum
        style: link
        icon_class: lorem-ipsum
        new_window: false
        no_follow: false
        type: action
      - label: lorem-ipsum
        url: lorem-ipsum
        style: link
        icon_class: lorem-ipsum
        new_window: false
        no_follow: false
        type: action
      - label: lorem-ipsum
        url: lorem-ipsum
        style: link
        icon_class: lorem-ipsum
        new_window: false
        no_follow: false
        type: action
      - label: lorem-ipsum
        url: lorem-ipsum
        style: link
        icon_class: lorem-ipsum
        new_window: false
        no_follow: false
        type: action
    type: header
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
